### PR TITLE
kind clusters: replace docker-cli commands with Docker Engine Go Client to improve podman compatibility

### LINKED ISSUE #408: kn quickstart kind - Error: creating cluster: docker not running
Hello,

I'm trying to use the quickstart plugin to get knative running and learn more about this tool.

I have podman 4.4.4 installed. The podman machine is running and I'm able to create a kind cluster running `kind create cluster`:

```shell
~
❯ kind create cluster
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.26.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋

~
❯
```

But when I try to run the command `kn quickstart kind`, i get the following error:

```shell
~
❯ kn quickstart kind
Running Knative Quickstart using Kind
Error: creating cluster: docker not running
Usage:
  kn-quickstart kind [flags]

Flags:
  -h, --help                        help for kind
      --install-eventing            install Eventing on quickstart cluster
      --install-serving             install Serving on quickstart cluster
  -k, --kubernetes-version string   kubernetes version to use (1.x.y) or (kindest/node:v1.x.y)
  -n, --name string                 kind cluster name to be used by kn-quickstart (default "knative")

creating cluster: docker not running
Error: exit status 1

~
❯
```

This is the S.O. version for the podman machine:

```shell
~
❯ podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Fedora CoreOS 37.20230401.2.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

[core@localhost ~]$ uname -a
Linux localhost.localdomain 6.2.8-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 22 19:11:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[core@localhost ~]$ exit
logout

~
❯
```

### LINKED ISSUE #528: containerd deprecated CRI hosts config
The old CRI config pattern for specifying registry.mirrors and registry.configs has been DEPRECATED.

See here:
* https://github.com/kubernetes-sigs/kind/issues/2875
* https://github.com/kubernetes/kubernetes/issues/110312

we use it in our `kind.go` file:
https://github.com/knative-extensions/kn-plugin-quickstart/blob/main/pkg/kind/kind.go#L314

Looks like we need to change and create a directory with a `hosts.toml` file for each host

### PR DESCRIPTION
**Pull request by chzar**
# Changes

Replaced the docker-cli commands in kind.go with github.com/docker/docker/client

/kind enhancement

Fixes #408
Fixes #528 

**Release Note**

```release-note
Improves cross compatibility between users of docker and podman (if docker compatibility mode is enabled). Removes the requirement of installing docker-cli for podman users.
```

**Docs**

```docs
Podman users should be instructed to enable Docker compatibility mode
```

### CODE REVIEW

**Comment by psschwei** [comment]
Thanks for the PR! You'll need to sign the CLA before we can merge this.
/ok-to-test

**Comment by chzar** [comment]
> Thanks for the PR! You'll need to sign the CLA before we can merge this. /ok-to-test

Signed, sealed, delivered.

**Comment by psschwei** [comment]
When trying this with podman, I got the following error:

```
Command Output: Error: rootlessport cannot expose privileged port 80, you can add 'net.ipv4.ip_unprivileged_port_start=80' to /etc/sysctl.conf (currently 1024), or choose a larger port number (>= 1024): listen tcp 0.0.0.0:80: bind: permission denied
```

I don't use podman on a regular basis, so not sure if regular podman users would already have a workaround for the port issue or if we should think about changing the host port on the cluster...

With docker, everything worked fine.

**Comment by chzar** [comment]
Sounds like you are using rootless podman and are not allowed to bind to port 80. https://github.com/containers/podman/blob/main/rootless.md

I am on macOS using podman machine so kind works as-is.

**Comment by psschwei** [comment]
> Perhaps changing to port 8080 or 9000 would be more appropriate for a test/demo setup?

Yeah, I think that makes sense... would you want to do that change too?

**Comment by chzar** [comment]
Sure. I can make a separate PR.

This change should work for all MacOS/Windows users of docker/podman. For Linux users, the restrictions on binding Port 80 have always been present for both docker and podman - so nothing is broken that wasn't so before.

File: pkg/kind/kind.go [hunk 1]
```diff
@@ -350,6 +454,12 @@ func parseKindVersion(v string) (float64, error) {
 	return floatVersion, nil
 }
 
-func deleteContainerRegistry() *exec.Cmd {
-	return exec.Command("docker", "rm", "-f", container_reg_name, "&&", "||", "true")
+func deleteContainerRegistry(dcli *dclient.Client) error {
+	if err := dcli.ContainerRemove(context.Background(), container_reg_name, container.RemoveOptions{Force: true}); err != nil {
```
Comment (psschwei) [inline pkg/kind/kind.go:458]: I think we need to check if a registry container is running first

Comment (chzar) [reply pkg/kind/kind.go:458]: Why would it matter if the container was running or stopped?

Comment (psschwei) [reply pkg/kind/kind.go:458]: Sorry, shouldn't have used the word "running" in my original comment... the issue isn't whether the registry container is running or stopped but rather if it exists or not. 

Because the `deleteContainerRegistry()` method now returns an error, the whole quickstart will fail if the registry container doesn't exist.

```
$ ./kn-quickstart kind --registry
Running Knative Quickstart using Kind
✅ Checking dependencies...
    Kind version is: 0.23.0
💽 Installing local registry...
Pulling from library/registry: 2
Digest: sha256:ac0192b549007e22998eb74e8d8488dcfe70f1489520c3b144a6047ac5efbe90: %!s(<nil>)
Status: Image is up to date for registry:2: %!s(<nil>)
Error: creating cluster: failed to delete local registry: failed remove registry container: Error response from daemon: No such container: kind-registry
```

whereas before quickstart wouldn't fail when trying to delete a non-existent registry.

Comment (chzar) [reply pkg/kind/kind.go:458]: Now I follow you. I will improve the error handling such that it does not return an error in this case instead of trying to check for the existence of the registry prior to deletion. It's possible that the registry container is deleted by another client prior to my delete container api call.

**Review by psschwei — COMMENTED** [review]
Thanks!
/lgtm
/approve
